# Generated by Django 5.2.8 on 2025-11-08 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
