# Generated by Django 5.2.8 on 2025-11-08 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_product_price_alter_product_if_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('founded_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2025)])),
                ('website', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='if_in_stock',
            new_name='in_stock',
        ),
    ]
