# Generated by Django 5.2.8 on 2025-11-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_company_rename_if_in_stock_product_in_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='companie',
        ),
    ]
